target_default: 0_config

targets:
  
  0_config:
    depends:
      - start_date
      - end_date
      - gw_param_cd
  
##-- Fetch configs --##
  
  start_date:
    command: as.Date(I('2020-11-27'))
  end_date:
    command: as.Date(I('2020-12-10'))
  
  gw_param_cd:
    command: c(I('72019'))

##-- Process configs --##

  date_for_pct_change:
    command: c(end_date)
  proj_str:
    command: c(I('+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs'))

##-- Visualize configs --##

  # Width and height are double what they need to be so that resolution looks good when created on Windows
  # Width/height are halved after video is created.
  # Need to be specified in inches.
  width: 
    command: I(24)
  height: 
    command: I(12)

##-- Animate configs --##
  
  video_input_framerate:
    command: I(2.25)
  video_output_framerate:
    command: I(2.25)
  gif_frame_delay:
    command: I(50)
