target_default: 0_config

targets:
  
##-- Historic data configs --##

  historic_start_date:
    command: as.Date(I('1800-01-01'))
  historic_end_date:
    command: as.Date(I('2020-12-31'))
  historic_fetch_size_limit:
    command: I(50)
  
  # Building these are completely decoupled from the rest of the pipeline
  # Use these objects in 1_fetch to s3_get the data
  historic_site_info_s3_fn:
    command: c(I('gw-conditions/historic_gw_site_info.rds.ind'))
  historic_data_s3_fn:
    command: c(I('gw-conditions/historic_gw_data.csv.ind'))
  historic_quantiles_s3_fn:
    command: c(I('gw-conditions/historic_gw_quantiles.csv.ind'))
  
##-- Fetch configs --##
  
  viz_start_date:
    command: as.Date(I('2020-10-01'))
  viz_end_date:
    command: as.Date(I('2020-12-31'))
  # This was a useful resource: https://anthonylouisdagostino.com/bounding-boxes-for-all-us-states/
  # Use bounding box in case we want to do this regionally someday
  # Must be west longitude, south latitude, east longitude, and then north latitude
  # Start with CONUS only
  viz_bounding_box:
   command: c(I(-124.409591), I(24.523096), I(-66.949895), I(49.384358))
  
  gw_param_cd:
    command: c(I('72019'))

##-- Process configs --##

  date_for_pct_change:
    command: c(viz_end_date)
  proj_str:
    command: c(I('+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs'))

##-- Visualize configs --##

  # Width and height are double what they need to be so that resolution looks good when created on Windows
  # Width/height are halved after video is created.
  # Need to be specified in inches.
  width: 
    command: I(24)
  height: 
    command: I(12)

##-- Animate configs --##
  
  video_input_framerate:
    command: I(2.25)
  video_output_framerate:
    command: I(2.25)
  gif_frame_delay:
    command: I(50)
