target_default: 0_config

targets:
  
##-- Historic data configs --##

  # Don't touch these unless you have a REALLY good reason because they
  # will trigger rebuilds of the historic pipeline and the instantaneous
  # part takes a VERY long time.
  historic_start_date:
    command: as.Date(I('1900-01-01'))
  historic_end_date:
    command: as.Date(I('2020-12-31'))
  historic_dv_fetch_size_limit:
    command: I(50)
  historic_uv_fetch_size_limit:
    command: I(10)
  
  # This one will initiate a rebuild of the quantiles (still lengthy, but not 
  # like redownloading the data, as the above trigger).
  historic_min_yrs_per_site_for_quantile_calc:
    command: I(3)
  historic_site_types_for_quantile_calc:
    command: c(I('GW'))
  
  # Building these are completely decoupled from the rest of the pipeline
  # Use these objects in 1_fetch to s3_get the data
  historic_unfiltered_site_info_s3_fn:
    command: c(I('gw-conditions/historic_gw_site_info_unfiltered.rds'))
  historic_unfiltered_data_s3_fn:
    command: c(I('gw-conditions/historic_gw_data_unfiltered.csv'))
  historic_filtered_data_s3_fn:
    command: c(I('gw-conditions/historic_gw_data_filtered.csv'))
  historic_filtered_site_info_s3_fn:
    command: c(I('gw-conditions/historic_gw_site_info_filtered.rds'))
  historic_quantiles_s3_fn:
    command: c(I('gw-conditions/historic_gw_quantiles.csv'))
  
##-- Fetch configs --##
  
  viz_start_date:
    command: as.Date(I('2019-10-01'))
  viz_end_date:
    command: as.Date(I('2020-09-30'))
  # Use bounding box in case we want to do this regionally someday
  # Start with CONUS only
  viz_bounding_box:
   command: fetch_usa_bbox(conus_only = TRUE)
  dv_fetch_size_limit:
    command: I(200)
  uv_fetch_size_limit:
    command: I(50)
  
  # DO NOT CHANGE UNLESS YOU WANT TO REBUILD ALL HISTORIC DATA, TOO!
  gw_param_cd:
    command: c(I('72019'))
  
  # Additional fetch params for the states that don't report 72019 pcode
  addl_gw_param_cd:
    command: c(I('62610'))
  addl_states:
    command: c(I('FL'), I('KS'))

##-- Process configs --##

  anomaly_categories:
    command: c(I("Very low"), I("Low"), I("Normal"), I("High"), I("Very high"))
  anomaly_bins:
    command: c(0, 10, 25, 75, 90, 100)
  # Albers Equal Area
  proj_str:
    command: c(I('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'))

##-- Visualize configs --##

  # SVG dims are in pixels
  svg_width: 
    command: I(1000)
  svg_height: 
    command: I(700)
  scico_palette:
    command: c(I('roma'))
    
##-- Animate configs --##
  
  
